#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
fi

# For Darwin, this is a workaround for https://github.com/gradle/gradle/issues/25036
if "$darwin" ; then
    # shellcheck disable=SC2039,SC3045
    MAX_FD=$( sysctl -n kern.maxfiles 2>/dev/null || echo 0 )
fi

# Attempt to set MAX_FD to the maximum supported by this system.
# Output a warning if this limit is lower than the maximum intended.
# shellcheck disable=SC2039,SC3045
if [ "$MAX_FD" -gt 0 ] 2>/dev/null && [ "$MAX_FD" -lt "${MAX_FD:-"${MAX_FD:-1024}"}" ] 2>/dev/null ; then
    warn "The maximum file descriptor limit of this system is too low for the Gradle wrapper to operate correctly. The Gradle wrapper needs a limit of at least ${MAX_FD} but the current limit is ${MAX_FD}."
fi

# Export Gradle's JVM options from the GRADLE_OPTS and JAVA_OPTS settings.
# These are also picked up by the Gradle wrapper in the gradle.properties file.
# For portability, export them as GRADLE_OPTS and JAVA_OPTS as well.
# Also export GRADLE_OPTS and JAVA_OPTS so that the Gradle wrapper can use them.
# shellcheck disable=SC2039,SC3045
export GRADLE_OPTS
export JAVA_OPTS

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * classpath
#   * -D... prefs (deprecated, don't use)
#   * @notify stacksize (deprecated, don't use)
#   * @notify stackframes (deprecated, don't use)
#   * -jar
#   * the wrapper jar

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#)}; t=/${t%%/*}             # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # temporary files we will write. The last unshift is not a temporary file;
        # it is the original entry in the args list that we will use later.
        shift                   # remove a temporary file from the front
        set -- "$@" "$arg"      # put the converted arg back
    done
fi


# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to the Gradle wrapper.
# For example, to pass JVM options to the Gradle daemon, set GRADLE_OPTS or JAVA_OPTS.
# For example:
#   export GRADLE_OPTS="-Dorg.gradle.jvmargs=-Xmx1024m"
#   export JAVA_OPTS="-Xmx1024m"
# These options are appended to the JVM command line when the Gradle wrapper is executed.

# Stop Gradle daemon if it's already running.
# This is a workaround for https://github.com/gradle/gradle/issues/25036
# It's only needed for the first build after a system restart.

eval "set -- \"\$@\""

# Stop Gradle daemon if it's already running.
# This is a workaround for https://github.com/gradle/gradle/issues/25036
# It's only needed for the first build after a system restart.

exec "$JAVACMD" \
    -classpath "$CLASSPATH" \
    -Dorg.gradle.appname="$APP_BASE_NAME" \
    -Dorg.gradle.home="$APP_HOME" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
